blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Documentation
    url: https://samuelyossef.com/
    about: Check the documentation for usage of Anse, or make improvements to it.
  - name: â±ï¸ Roadmap
    url: 
    about: Explore upcoming features.
  - name: ğŸ’¬ Discussions
    url: 
    about: Use discussions if you have an idea for improvement or for asking questions.
